### ISSUE TITLE
SECRET_KEY published

### ISSUE THREAD

**Issue by adewes** [orges/ITSY#6]
It seems that you've published your `SECRET_KEY` in your repository:

https://www.quantifiedcode.com/app#/project/gh:orges:ITSY?groups=code_patterns%3A1Wit6MHp%3Af0

**Comment by orges** [comment]
Hi, it is overriden by real live settings on live server... it is unused. ;)

**Comment by adewes** [comment]
ok just wanted to be sure!

**Comment by orges** [comment]
Thank you by the way, I didn't know quantifiedcode.com before, it sounds great!
